### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by jl2035** [bitfloor/trader.nodejs#6]
Running this command:
npm install git://github.com/bitfloor/trader.nodejs.git

returns this: http://pastebin.com/zjkBRmdy

Please help...

**Comment by pskupinski** [comment]
You're going to need node 0.8 or lower in order to use node-waf which a dependency(microtime 0.2.0) requires.  node-waf was removed in 0.10 and deprecated in 0.8.

Assuming bitfloor will resume trading one day and wants to update this module they should go through and update their dependencies and specify a version of node.js they want to target in their package.json.

**Comment by jl2035** [comment]
Thanks.. it can't help me than... :(
